odom0: /robot1/odom
odom0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]

odom1: /robot1/laser_odom
odom1_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]

map_frame: robot1_odom
odom_frame: robot1_odom
base_link_frame: robot1_base_link
world_frame: robot1_odom
frequency: 30
sensor_timeout: 0.1
two_d_mode: true
